apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-app1
  template:
    metadata:
      labels:
        app: grpc-app1
    spec:
      containers:
        - name: grpc-app1
          image: your-docker-repo/grpc-app1:latest
          ports:
            - containerPort: 50051
